runtime: nodejs18

network:
   forwarded_ports:
      - 65080
   instance_tag: websocket

env_variables:
   DB_USER: root
   DB_NAME: foundark_db
   DB_PASS: password
   DB_INSTANCE: found-ark-backend:us-west1:foundarkbe
